site_name: WordSiv
site_url: https://mydomain.org/mysite
theme:
  palette:
    primary: amber
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: "index.md"
  - Getting Started: "getting-started.md"
  - Usage:
      - Importing WordSiv: "usage/importing.md"
      - Language Support: "usage/language-support.md"
      - Letter Case: "usage/letter-case.md"
      - Repeatable Text Generation: "usage/repeatable-generation.md"
      - Tuning Word Selection: "usage/tuning-word-selection.md"
      - Punctuation: "usage/punctuation.md"
  - API Reference:
      wordsiv:
        wordsiv: "api-reference.md"
  - Contributing: "contributing.md"
  - Release Notes: "release-notes.md"
repo_url: https://github.com/tallpauley/wordsiv
watch:
  - wordsiv
plugins:
  - autorefs
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [wordsiv]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            inherited_members:
              - Vocab
            docstring_options:
              ignore_init_summary: true
            show_labels: true
            separate_signature: true
            preload_modules:
              - wordsiv
            signature_crossrefs: true
            summary:
              attributes: true
              modules: false
              functions: true
              classes: true
            docstring_style: google
            cross_references: true
