site_name: WordSiv
site_url: https://mydomain.org/mysite
theme:
  palette:
    primary: amber
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.superfences
nav:
  - Introduction: "index.md"
  - Guide:
      - Quickstart: guide/quickstart.md
      - Basic Usage: guide/basic-usage.md
      - Generating Text: guide/generating-text.md
      - Filtering Words: guide/filtering-words.md
      - Letter Case: guide/letter-case.md
      - Tuning Word Selection: guide/"tuning-word-selection.md
      - Repeatable Proofs: guide/repeatable-proofs.md
      - Adding Language Support: guide/adding-language-support.md
  - API Reference:
      wordsiv:
        wordsiv: "api-reference.md"
  - Contributing: "contributing.md"
  - Release Notes: "release-notes.md"
repo_url: https://github.com/tallpauley/wordsiv
watch:
  - wordsiv
plugins:
  - autorefs
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [wordsiv]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            inherited_members:
              - Vocab
            docstring_options:
              ignore_init_summary: true
            show_labels: true
            separate_signature: true
            preload_modules:
              - wordsiv
            signature_crossrefs: true
            summary:
              attributes: true
              modules: false
              functions: true
              classes: true
            docstring_style: google
            cross_references: true
